language: ruby

sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/frontend/node_modules

before_install:
  - npm install -g ember-cli bower
  - cd $TRAVIS_BUILD_DIR/frontend; npm install
  - cd $TRAVIS_BUILD_DIR/frontend; bower install

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate test

script:
  - cd $TRAVIS_BUILD_DIR/frontend; ember test # Execute the Ember tests
  - rake test # Execute the Rails tests
