language: ruby

sudo: false

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/frontend/node_modules
    - $TRAVIS_BUILD_DIR/frontend/bower_components

before_install:
  - cd $TRAVIS_BUILD_DIR/frontend; npm install

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate test

script:
  - cd $TRAVIS_BUILD_DIR/frontend; npm test # Execute the Ember tests
  - rake test # Execute the Rails tests
